### ISSUE TITLE
Can't install on Redmi Note 7

### ISSUE THREAD

**Issue by dotridat** [tareksander/termux-gui-package#12] opened 2022-10-14 08:38 UTC
![Screenshot_2022-10-14-16-37-11-712_com miui packageinstaller](https://user-images.githubusercontent.com/112381932/195802131-90ef93c9-5ff5-4b7d-bcf3-4c7c7ff72f8a.jpg)

**Comment by tareksander** [comment] 2022-10-14 09:00
Duplicate of [this](https://github.com/termux/termux-gui/issues/4).

**Closed** 2022-10-14 09:00 UTC
